const employeeData = [
  {
    id: 1,
    name: "John Doe",
    role: "Software Engineer",
    email: "john.doe@example.com",
    status: "Active",
  },
  {
    id: 2,
    name: "Jane Smith",
    role: "Product Manager",
    email: "jane.doe@example.com",
    status: "Inactive",
    icon: "...",
  },
  {
    id: 3,
    name: "Alice Johnson",
    role: "Data Analyst",
    email: "alice.doe@example.com",
    status: "Active",
    icon: "...",
  },
  {
    id: 4,
    name: "Bob Williams",
    role: "UI/UX Designer",
    email: "bob.doe@example.com",
    status: "Active",
    icon: "...",
  },
  {
    id: 5,
    name: "Michael Brown",
    role: "Frontend Developer",
    email: "michael.doe@example.com",
    status: "Active",
    icon: "...",
  },
  {
    id: 6,
    name: "Sarah Taylor",
    role: "Backend Developer",
    email: "sarah.doe@example.com",
    status: "Inactive",
    icon: "...",
  },
  {
    id: 7,
    name: "David Clark",
    role: "System Administrator",
    email: "david.doe@example.com",
    status: "Active",
    icon: "...",
  },
  {
    id: 8,
    name: "Emily Anderson",
    role: "HR Manager",
    email: "emily.doe@example.com",
    status: "Active",
    icon: "...",
  },
  {
    id: 9,
    name: "Daniel Martinez",
    role: "Marketing Specialist",
    email: "daniel.doe@example.com",
    status: "Inactive",
    icon: "...",
  },
  {
    id: 10,
    name: "Olivia White",
    role: "Graphic Designer",
    email: "olivia.doe@example.com",
    status: "Active",
    icon: "...",
  },
  {
    id: 5,
    name: "Michael Brown",
    role: "Frontend Developer",
    email: "michael.doe@example.com",
    status: "Active",
    icon: "...",
  },
  {
    id: 6,
    name: "Sarah Taylor",
    role: "Backend Developer",
    email: "sarah.doe@example.com",
    status: "Inactive",
    icon: "...",
  },
  {
    id: 7,
    name: "David Clark",
    role: "System Administrator",
    email: "david.doe@example.com",
    status: "Active",
    icon: "...",
  },
  {
    id: 8,
    name: "Emily Anderson",
    role: "HR Manager",
    email: "emily.doe@example.com",
    status: "Active",
    icon: "...",
  },
  {
    id: 9,
    name: "Daniel Martinez",
    role: "Marketing Specialist",
    email: "daniel.doe@example.com",
    status: "Inactive",
    icon: "...",
  },
  {
    id: 10,
    name: "Olivia White",
    role: "Graphic Designer",
    email: "olivia.doe@example.com",
    status: "Active",
    icon: "...",
  },
];

export default employeeData;
